// application-ui-v4/react/layout/media-objects/08-nested.jsx
export default function Example() {
  return (
    <div className="flex">
      <div className="mr-4 shrink-0">
        <svg
          fill="none"
          stroke="currentColor"
          viewBox="0 0 200 200"
          preserveAspectRatio="none"
          aria-hidden="true"
          className="size-16 border border-gray-300 bg-white text-gray-300 dark:border-white/15 dark:bg-gray-900 dark:text-white/15"
        >
          <path d="M0 0l200 200M0 200L200 0" strokeWidth={1} vectorEffect="non-scaling-stroke" />
        </svg>
      </div>
      <div>
        <h4 className="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
        <p className="mt-1 text-gray-500 dark:text-gray-400">
          Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus
          quidem ipsam quia iusto.
        </p>

        <div className="mt-6 flex">
          <div className="mr-4 shrink-0">
            <svg
              fill="none"
              stroke="currentColor"
              viewBox="0 0 200 200"
              preserveAspectRatio="none"
              aria-hidden="true"
              className="size-12 border border-gray-300 bg-white text-gray-300 dark:border-white/15 dark:bg-gray-900 dark:text-white/15"
            >
              <path d="M0 0l200 200M0 200L200 0" strokeWidth={1} vectorEffect="non-scaling-stroke" />
            </svg>
          </div>
          <div>
            <h4 className="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
            <p className="mt-1 text-gray-500 dark:text-gray-400">
              Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus
              quidem ipsam quia iusto.
            </p>
          </div>
        </div>
        <div className="mt-6 flex">
          <div className="mr-4 shrink-0">
            <svg
              fill="none"
              stroke="currentColor"
              viewBox="0 0 200 200"
              preserveAspectRatio="none"
              aria-hidden="true"
              className="size-12 border border-gray-300 bg-white text-gray-300 dark:border-white/15 dark:bg-gray-900 dark:text-white/15"
            >
              <path d="M0 0l200 200M0 200L200 0" strokeWidth={1} vectorEffect="non-scaling-stroke" />
            </svg>
          </div>
          <div>
            <h4 className="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
            <p className="mt-1 text-gray-500 dark:text-gray-400">
              Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus
              quidem ipsam quia iusto.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

// application-ui-v4/vue/layout/media-objects/08-nested.vue
<template>
  <div class="flex">
    <div class="mr-4 shrink-0">
      <svg class="size-16 border border-gray-300 bg-white text-gray-300 dark:border-white/15 dark:bg-gray-900 dark:text-white/15" preserveAspectRatio="none" stroke="currentColor" fill="none" viewBox="0 0 200 200" aria-hidden="true">
        <path vector-effect="non-scaling-stroke" stroke-width="1" d="M0 0l200 200M0 200L200 0" />
      </svg>
    </div>
    <div>
      <h4 class="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
      <p class="mt-1 text-gray-500 dark:text-gray-400">Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus quidem ipsam quia iusto.</p>

      <div class="mt-6 flex">
        <div class="mr-4 shrink-0">
          <svg class="size-12 border border-gray-300 bg-white text-gray-300 dark:border-white/15 dark:bg-gray-900 dark:text-white/15" preserveAspectRatio="none" stroke="currentColor" fill="none" viewBox="0 0 200 200" aria-hidden="true">
            <path vector-effect="non-scaling-stroke" stroke-width="1" d="M0 0l200 200M0 200L200 0" />
          </svg>
        </div>
        <div>
          <h4 class="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
          <p class="mt-1 text-gray-500 dark:text-gray-400">Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus quidem ipsam quia iusto.</p>
        </div>
      </div>
      <div class="mt-6 flex">
        <div class="mr-4 shrink-0">
          <svg class="size-12 border border-gray-300 bg-white text-gray-300 dark:border-white/15 dark:bg-gray-900 dark:text-white/15" preserveAspectRatio="none" stroke="currentColor" fill="none" viewBox="0 0 200 200" aria-hidden="true">
            <path vector-effect="non-scaling-stroke" stroke-width="1" d="M0 0l200 200M0 200L200 0" />
          </svg>
        </div>
        <div>
          <h4 class="text-lg font-bold text-gray-900 dark:text-white">Lorem ipsum</h4>
          <p class="mt-1 text-gray-500 dark:text-gray-400">Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus quidem ipsam quia iusto.</p>
        </div>
      </div>
    </div>
  </div>
</template>
