// application-ui-v4/react/forms/input-groups/16-input-with-inset-label.jsx
export default function Example() {
  return (
    <div className="rounded-md bg-white px-3 pt-2.5 pb-1.5 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600 dark:bg-white/5 dark:outline-white/10 dark:focus-within:outline-indigo-500">
      <label htmlFor="name" className="block text-xs font-medium text-gray-900 dark:text-gray-200">
        Name
      </label>
      <input
        id="name"
        name="name"
        type="text"
        placeholder="Jane Smith"
        className="block w-full text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6 dark:bg-transparent dark:text-white dark:placeholder:text-gray-500"
      />
    </div>
  )
}

// application-ui-v4/vue/forms/input-groups/16-input-with-inset-label.vue
<template>
  <div class="rounded-md bg-white px-3 pt-2.5 pb-1.5 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600 dark:bg-white/5 dark:outline-white/10 dark:focus-within:outline-indigo-500">
    <label for="name" class="block text-xs font-medium text-gray-900 dark:text-gray-200">Name</label>
    <input type="text" name="name" id="name" class="block w-full text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6 dark:bg-transparent dark:text-white dark:placeholder:text-gray-500" placeholder="Jane Smith" />
  </div>
</template>
