// application-ui-v4/react/headings/section-headings/09-with-label.jsx
export default function Example() {
  return (
    <div className="border-b border-gray-200 pb-5 dark:border-white/10">
      <div className="-mt-2 -ml-2 flex flex-wrap items-baseline">
        <h3 className="mt-2 ml-2 text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
        <p className="mt-1 ml-2 truncate text-sm text-gray-500 dark:text-gray-400">in Engineering</p>
      </div>
    </div>
  )
}

// application-ui-v4/vue/headings/section-headings/09-with-label.vue
<template>
  <div class="border-b border-gray-200 pb-5 dark:border-white/10">
    <div class="-mt-2 -ml-2 flex flex-wrap items-baseline">
      <h3 class="mt-2 ml-2 text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
      <p class="mt-1 ml-2 truncate text-sm text-gray-500 dark:text-gray-400">in Engineering</p>
    </div>
  </div>
</template>
