// application-ui-v4/react/headings/card-headings/02-with-action.jsx
export default function Example() {
  return (
    <div className="border-b border-gray-200 px-4 py-5 sm:px-6 dark:border-white/10">
      <div className="-mt-2 -ml-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
        <div className="mt-2 ml-4">
          <h3 className="text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
        </div>
        <div className="mt-2 ml-4 shrink-0">
          <button
            type="button"
            className="relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:bg-indigo-500 dark:shadow-none dark:hover:bg-indigo-400 dark:focus-visible:outline-indigo-500"
          >
            Create new job
          </button>
        </div>
      </div>
    </div>
  )
}

// application-ui-v4/vue/headings/card-headings/02-with-action.vue
<template>
  <div class="border-b border-gray-200 px-4 py-5 sm:px-6 dark:border-white/10">
    <div class="-mt-2 -ml-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="mt-2 ml-4">
        <h3 class="text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
      </div>
      <div class="mt-2 ml-4 shrink-0">
        <button type="button" class="relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:bg-indigo-500 dark:shadow-none dark:hover:bg-indigo-400 dark:focus-visible:outline-indigo-500">Create new job</button>
      </div>
    </div>
  </div>
</template>
