// application-ui-v4/vue/forms/input-groups/05-input-with-hidden-label.vue
<template>
  <div>
    <input type="email" name="email" id="email" aria-label="Email" class="block w-full rounded-md bg-white px-3 py-1.5 text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500" placeholder="you@example.com" />
  </div>
</template>

// application-ui-v4/react/forms/input-groups/05-input-with-hidden-label.jsx
export default function Example() {
  return (
    <div>
      <input
        id="email"
        name="email"
        type="email"
        placeholder="you@example.com"
        aria-label="Email"
        className="block w-full rounded-md bg-white px-3 py-1.5 text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
      />
    </div>
  )
}
